default: &default
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  timeout: 5000

development:
  <<: *default
  url:  "postgres://{aact-login}:{aact-password}@aact-db.ctti-clinicaltrials.org:5432/aact"

test:
  <<: *default
  url:  "postgres://{aact-login}:{aact-password}@aact-db.ctti-clinicaltrials.org:5432/aact"

production:
  <<: *default
  url:  "postgres://{aact-login}:{aact-password}@aact-db.ctti-clinicaltrials.org:5432/aact"

