module Lookup
  class Keyword < SuperLookup
    self.table_name = 'lookup.keywords'

    def self.source_data
      # The model that will be used as the source of info
      "Ctgov::Keyword"
    end

    def self.names_to_ignore
      ['e-do', 'sade-free rate','0177','11-041','11-101','11-104','11-105','11-106','11-108','1000 days', '11-150',
       '11q','11-136','qqwqb','12-116','12-117','12-121','12-124','11q','124-i','14-101','18fdg','10 mg','10q23.3','11q-deleted relapsed/refractory chronic lymphocytic leukaemia',
       '24-hr diet recall','24 hour urine','24-hour dietary recall','24-hour dietary recalls','24-hour energy intake','24-hour pad test','24-hour urine','24-hout urine',
      '24-h recall','24-h urine composition''24-week follow-up','2nd line','2nd trimester','30 day mortality', '30-day mortality', '30 day readmission rate','3d acquisition',
'blood lines','abdominal-based breast reconstruction','enteric-coated mycophenolate sodium (ec-mps),', 'non obstructive', 'non-obstructive', 
      '3d guide','30 mg','95gy in 35 fractions','5 years','97-127','abcsg','ablc','abnormal fasting glucose','abnormal gait','academic stress','acupression','iatta', 'abdominal operation','ict support','accelerated healing','adaptable','admissions','i-cam','abstain','acld','abuse report','healthy meals','da-90','creative arts',
      'gsk pandemic candidate vaccine','gorham','everest','g72','cravings','hattr','frost injury','gow-gates nerve block','cup of tea','cramps','especialista',
      'food records', 'gargle','guilty', 'at-risk','levels', 'enhanced','hcmv infection','gluten immunogenic peptides','current disease','congenital long qt',
'concurrent chemoradiation therapy','carob','s-lar','dialysis clinic','ksi-301','tzh-chi esbl study','gold miners', 'low-risk','low risk, localized prostate cancer',
      'cd-163','neglect','ongoing', 'certs', 'fetal','clinical','infection, quality of life, lung injury','id','pest','disease-free adult males',
      'id-cap medication adherence feedback system','muscle diseases','tooth-brushing program','disorder,','icd-pacemaker',
      'icd, home monitoring, cardiomessenger, implant','multi-food allergic','generalized','dislocation','gene-enviroment interaction','multi-week',
      'multiple-channel port laparoscopy','multi-purpose solution','multi-vessel disease','multi-centre cohort study','multiple-transfer-effects',
      'multi-purpose solution','gene-enviroment interaction','pr+','pr-negative','renal and pancreas transplantation','rating scales'
      ]
    end

    def self.possible_descriptions
      [
       'disease',
       'medical condition',
       'disorder',
       'defect',
       'disturbance',
      ]
    end

    def self.impossible_descriptions
      super + [
       'abstract',
       'actress',
       'airplane',
       'army general',
       'artillery guns',
       'artwork',
       'asteroid',
       'business',
       'aviation squadron',
       'book',
       'brand of footwear',
       'clinical commissioning group',
       'clinical trial',
       'comic book series',
       'company',
       'conference',
       'confections',
       'driving license',
       'episode',
       'etching',
       'exhibition',
       'farmhouse',
       'galaxy',
       'governmental agency',
       'grammatical case',
       'hospitals',
       'internet bank',
       'interpro family',
       'journal',
       'light table is a viewing device',
       'literature review',
       'magazine',
       'mountain in',
       'musical composition',
       'musical group',
       'musical duo',
       'non-profit',
       'norwegian',
       'organization',
       'motorway',
       'novel by',
       'person',
       'place for conducting research',
       'pokémon move',
       'presenter',
       'proposed ethernet standard',
       'publisher',
       'report',
       'rock band',
       'route',
       'rural commune',
       'scholarly article',
       'short story',
       'single by',
       'specialist',
       'sports club',
       'store which sells nutrition supplements',
       'teleplay',
       'television series',
       'technical information service',
       'town in ',
       'type of dam',
       'unincorporated community',
       'university',
       'watercourse',
       'webcomic',
       'extended play',
       'wikipedia',
       'zoroaster',
      ].flatten
    end

    def self.predefined_qcode
      # Most common - ordered list.
      {
        'HIV'                                      => 'Q15787',
        'Obesity'                                  => 'Q12174',
        'Pharmacokinetics'                         => 'Q323936',
        'Depression'                               => 'Q42844',
        'Safety'                                   => 'Q10566551',
        'Cancer'                                   => 'Q12078',
        'Pain'                                     => 'Q81938',
        'Exercise'                                 => 'Q219067',
        'COPD'                                     => 'Q199804',
        'Diabetes'                                 => 'Q12206',
        'Quality of Life'                          => 'Q13100823',
        'Children'                                 => 'Q7569',
        '10% urea'                                 => 'Q48318',
        '11 beta-hydroxysteroid dehydrogenase type 1' =>  'Q1145920',
        '11-beta-hydroxysteroid dehydrogenase type 1' =>  'Q1145920',
        '11beta-hydroxysteroid dehydrogenase type 1' => 'Q1145920',
        '23andme'                                    => 'Q216272',
        '25-hydroxy vitamin d'                       => 'Q139307',
        '25 hydroxy vitamin d'                       => 'Q139307',
        '25-hydroxyvitamin d3'                       => 'Q139307',
        '25ohd'                                      => 'Q139307',
        '25-oh d'                                    => 'Q139307',
        '2hr -75gm oral glucose tolerance test'      => 'Q1501412',
        '3d computed tomography'                     => 'Q32566',
        '68ga-dotanoc pet'                           => 'Q83445886',
        '68ga-dotanoc pet/ct'                        => 'Q83445886',
        '68ga-dotanoc'                              => 'Q83445886',
        'ga68-citrate'                              => 'Q27288064',
        '6-aminocaproic acid'                       =>'Q27132370',
        'abdominal'                                 => 'Q9597',
        'frmi'                                      => 'Q903809',
        'low- and middle-income country'            => 'Q1454602',
        'west africa'                               => 'Q4412',
        'bold effect'                               => 'Q796855',
        'world health organization (who)'           => 'Q7817',
        'grandmothers'                              => 'Q9235758',
        'crossfit'                                  => 'Q2072840',
        'sexual assault'                            => 'Q673281',
        'frozen plasma (fp)'                        => 'Q1225698',
        'nervous system diseases'                   => 'Q6996973',
        'smoker'                                    => 'Q18809854',
        'oral disease'                              => 'Q71362181',
        "traveler's"                                => 'Q138885',
        'shuti'                                     => 'Q66070585',
        'disease-free five-years survival'          => 'Q67402151',
        'muscle tissue'                             => 'Q797559',
        'pneumonia,'                                => 'Q12192',
        'ep &amp; belinostat'                       => 'Q4882925',
        'musculoskeletal, physical therapy'         => 'Q186005',
        'multi-drug resistant tb'                   => 'Q866602',
        'insula'                                    => 'Q1422654',
      }
    end
  end
end
